<a href="https://colab.research.google.com/github/oscmoral/Programacion-para-analitica-descriptiva-y-predictiva/blob/main/Practica4_Manipulacion_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Nombre: Oscar Morales Martinez
### Carrera: Maestría en Inteligencia Artificial y Analítica de Datos
### Materia: Programación para analítica descriptiva y predictiva


---



**Practica: Manipulación de matrices**

Objetivo: Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

1.   Suma ambas matrices.
2.   Resta la segunda matriz de la primera.
3.   Multiplica la primera matriz por 2.
4.   Realiza una multiplicación matricial entre las dos matrices.

Paso 1: Para manejar elementos aleatorios importamos la libreria "random"

In [ ]:
import random

Paso 2: Creamos las dos matrices 3x3 con valores aleatorios utilizando listas anidadas

In [ ]:
matrix_a = [[random.randint(1, 10) for _ in range(3)] for _ in range(3)]
matrix_b = [[random.randint(1, 10) for _ in range(3)] for _ in range(3)]

print("Matriz A:")
for row in matrix_a:
    print(row)

print("\nMatriz B:")
for row in matrix_b:
    print(row)

Matriz A:
[8, 3, 7]
[9, 4, 6]
[8, 1, 10]

Matriz B:
[6, 10, 8]
[1, 9, 10]
[2, 7, 3]


Paso 3: Sumamos las matrices

In [ ]:
sum_matrix = [
    [matrix_a[i][j] + matrix_b[i][j] for j in range(3)]
    for i in range(3)
]

print("\nSuma de A + B:")
for row in sum_matrix:
    print(row)


Suma de A + B:
[14, 13, 15]
[10, 13, 16]
[10, 8, 13]


Paso 4: Restamos las matrices

In [ ]:
sub_matrix = [
    [matrix_a[i][j] - matrix_b[i][j] for j in range(3)]
    for i in range(3)
]

print("\nResta de A - B:")
for row in sub_matrix:
    print(row)


Resta de A - B:
[2, -7, -1]
[8, -5, -4]
[6, -6, 7]


Paso 5: Multiplicamos la matriz A por 2

In [ ]:
scalar_matrix = [
    [value * 2 for value in row]
    for row in matrix_a
]

print("\nMatriz A multiplicada por 2:")
for row in scalar_matrix:
    print(row)


Matriz A multiplicada por 2:
[16, 6, 14]
[18, 8, 12]
[16, 2, 20]


Paso 6: Multiplicamos la matriz (A x B)

In [ ]:
mul_matrix = [[0 for _ in range(3)] for _ in range(3)]

for i in range(3):
    for j in range(3):
        for k in range(3):
            mul_matrix[i][j] += matrix_a[i][k] * matrix_b[k][j]

print("\nMultiplicación matricial A x B:")
for row in mul_matrix:
    print(row)


Multiplicación matricial A x B:
[65, 156, 115]
[70, 168, 130]
[69, 159, 104]




---

La primera parte de la practica la hicimos de modo manual pero me gustaria mostrar como podria resolverse el problema utilizando la libreria "NumPy"



---



Paso 1: importamos la libreria NumPy

In [ ]:
import numpy as np

Paso 2: Creamos las matrices utilizando la libreria NumPy

In [ ]:
matrix_a = np.random.randint(1, 11, (3, 3))
matrix_b = np.random.randint(1, 11, (3, 3))

print("Matriz A:")
print(matrix_a)

print("Matriz B:")
print(matrix_b)

Matriz A:
[[8 1 7]
 [4 9 1]
 [4 1 3]]
Matriz B:
[[ 2  7  9]
 [ 5 10  6]
 [ 4 10  7]]


Paso 3: Las operaciones podrian quedar reducidas a lo siguiente:

In [ ]:
print("Suma:\n", matrix_a + matrix_b)
print("Resta:\n", matrix_a - matrix_b)
print("Escalar x2:\n", matrix_a * 2)
print("Multiplicación matricial:\n", matrix_a @ matrix_b)

Suma:
 [[10  8 16]
 [ 9 19  7]
 [ 8 11 10]]
Resta:
 [[ 6 -6 -2]
 [-1 -1 -5]
 [ 0 -9 -4]]
Escalar x2:
 [[16  2 14]
 [ 8 18  2]
 [ 8  2  6]]
Multiplicación matricial:
 [[ 49 136 127]
 [ 57 128  97]
 [ 25  68  63]]
